[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
print_width = 120
single_quote = false